### ISSUE TITLE
MongoConector change the name of the collection

### ISSUE THREAD

**Issue by Vonisoa** [mk45/MongoConnector#12]
Hi all, how can I avoid MongoConnector to change the name of the collection when opening it as layer in qgis?
For example I have a collection named : `mycollection` and when opening it to qgis from mongoconnector, its name become `mycollection-a3c5`

**Comment by mk45** [comment]
You can't
It is often that I added the same collection a few times to indicate various aspects of the data ... 
I wanted to have a collection name in layer name and in the same time identify what I do with presented data on which layer... that what this '-****' is for.

Probably this is a feature for the next release

**Comment by Vonisoa** [comment]
OK, than you for the explanation!
