### ISSUE TITLE
Cannot check geojson gemometry box, then select field or select field, then check geojson gemometry box

### ISSUE THREAD

**Issue by taatuut** [mk45/MongoConnector#13]
Hi, I just installed MongoConnector 1.2.3 on QGIS 3.18.1. The plugin connects to my local mongodb instance and I can browse the databases and collections. However, I cannot check geojson gemometry box, and then select field or select field because as soon as I check the box it errors with:

`Error: index 0 has type 'QgsPoint' but 'QgsPointXY' is expected`

I can also not do it the other way around by selecting geometry field first and then checking box because when I select the geojson field it errors directly with:

`Error: Unknown geometry in object 60624c78df5f916ef9340914`

How can I either check the geojson gemometry box first and then still select field, or vice versa without getting an error after first part? Or, if I'm misunderstanding the functionality, what should I change when I want to check the geojson gemometry box and select the appropriate field?

**Comment by mk45** [comment]
Hi, can you share few features from your data? 

I will try to make release of 1.3.0 (is in GitHub but not in plugins site) in a few days.

**Comment by mk45** [comment]
Can You give more rows from console output ( More from error description like : line number , screenshots)

**Comment by mk45** [comment]
It seems like you should especially test how geometry looks in object 60624c78df5f916ef9340914

**Comment by mk45** [comment]
Yes I found a bug. Thanks ... Fixig.

**Comment by mk45** [comment]
Version 1.3.1 is pushed but we wait till Qgis accepts it

**Comment by taatuut** [comment]
Thanks for the quick follow up! Looking forward to test version 1.3.1 when available.

**Comment by mk45** [comment]
Please don't forget to leave Your feedback. So I know I can close the Issue

**Comment by taatuut** [comment]
I confirm that version 1.3.1 works! Happy to see how quick this was fixed, thanks. I'll dive into the MongoConnector a bit more the coming time.
