### ISSUE TITLE
Error QGIS 2.8.2 on ArchLinux

### ISSUE THREAD

**Issue by samtux** [mk45/MongoConnector#2]
I get the next error in Arch Linux and QGIS 2.8.2:

``` Python
No se pudo cargar el complemento MongoConnector-master debido a un error al llamar a su método classFactory()


Traceback (most recent call last):
  File "/usr/share/qgis/python/qgis/utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/samtux/.qgis2/python/plugins/MongoConnector-master/__init__.py", line 26, in classFactory
    from MongoConnector.plugin import MongoConnectorPlugin
  File "/usr/share/qgis/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named MongoConnector.plugin


Versión de Python:
2.7.10 (default, May 26 2015, 04:16:29) 
[GCC 5.1.0]
```

**Comment by mk45** [comment]
github adds this strange -master suffix to directory try to remove it as workaround im about to handle this ASAP
so You have to have /home/samtux/.qgis2/python/plugins/MongoConnector/
instead of  /home/samtux/.qgis2/python/plugins/MongoConnector-master/

**Comment by samtux** [comment]
I think it's a general error, since I installed from the plugins manager of QGIS.

Thanks for your reply @mk45

**Comment by mk45** [comment]
I thank You for this issue information.
I uploaded new plugin to qgis repository without -master suffix. It can be downloaded easly now.
Unfortunately old one must been removed completly.
I'm closing issue
