### ISSUE TITLE
Make the exceptions more verbose

### ISSUE THREAD

**Issue by mbourqui** [mk45/MongoConnector#3]
It's really hard to spot the issues in the data with only a single line and generic error message.
Would it be possible to include some hints about the corrupted data, like a document id or the actual item that raised the exception?

**Comment by mk45** [comment]
What is Your error message ? Can You give me example of corrupted data, or the way they might be corrupted. Did You find/know what caused exception in your case? Did You saw example ? 
Ok I will start to work on such feature.

**Comment by mbourqui** [comment]
The error message is: _Collection or collections geometry is improper_
I am currently looking for a sample of corrupted, but as I have 200K points, it's not that simple...
Thank you!

**Comment by mbourqui** [comment]
In my particular case, I had a numeric feature containing _NaN_'s.

**Comment by mk45** [comment]
Once again thank You for spotting this inconvenience. I will fix that but not before Eastern Holidays.

**Comment by mbourqui** [comment]
You're welcome! If I had more time, I would have make a pull request, but I am a bit busy those days.

**Comment by mbourqui** [comment]
Actually, a second source of failure was that one of my features was not present in every document.

**Comment by mk45** [comment]
I've made new version with very verbose exceptions. It is uploaded to QGIS plugins page and ready for download. You may test this version on Your corrupted data and see if it is ok. I'm waiting for feedback.

**Comment by mbourqui** [comment]
I tried with missing keys, and it works great!
Thank you very much :smiley:

**Comment by mk45** [comment]
Please vote 5 stars for plugin if you wish :P. I'm closing this ticket.
