### ISSUE TITLE
Error: Field XXX missing in object

### ISSUE THREAD

**Issue by stefanocudini** [mk45/MongoConnector#7]
"Error: Field <FIELDNAME> missing in object"

trying to connect to my database having documents with different structure

in mongodb the collection can contain different documents so I do not think this should be a limit for this plugin

@mk45 perhaps we need to eliminate the piece of code that controls the homogeneity of the documents structure, otherwise there will always be many incompatibilities with most of the mongodb databases

**Comment by stefanocudini** [comment]
https://github.com/mk45/MongoConnector/blob/1e93ee0c7496839f7824b5f6dda5b63665231f25/qgsmongolayer.py#L205

**Comment by mk45** [comment]
The limitation comes actually from QGIS itself. MongoDB is of course schemaless but QGIS is not. QGIS requires a fixed set of fields for layer. In MongoConnector plugin we try to infer this set from the first element.

https://github.com/mk45/MongoConnector/blob/1e93ee0c7496839f7824b5f6dda5b63665231f25/qgsmongolayer.py#L45

This might not be the best practice nevertheless is valid in most cases.

Of course, this may be solved in a different way ex.:
- `Get the minimum set of fields.` Set of fields that appear in all collection documents. I considered this approach as kind dangerous. One missing field in only one document might cause in dropping whole column behind the scene.

- `Get the maximum set of fields.` Set of fields that appear in any of collection document. In this case, we must handle the default values for each missing field. Assuming NULL might be even more dangerous.  

In both cases, the whole data set lookup is required.

In the current approach where we provide the document `_id` and missing field name that later might be provided sounds not bad at all.

As MongoDB is flexible we strongly advise creating the new collection with documents that contain only the desired set of fields.

**Comment by stefanocudini** [comment]
damn! :(

@mk45 It's a few hours I'm looking but I can not find an tool or lib(npm o python) to normalize my mongo database..
I understand the problem and it also has sense, unfortunately my database is very large and contains many different documents

**Comment by stefanocudini** [comment]
I'm created it to clone a collection with oncly valued documents

https://gist.github.com/stefanocudini/a4501eecf6922efb5d475f8dc934df67
