### ISSUE TITLE
Please remove `__MACOSX` dir

### ISSUE THREAD

**Issue by pcav** [mk45/MongoConnector#9]
This causes unwanted red warning in the plugin interface.
Thanks.

**Comment by mk45** [comment]
Done in version 1.2.1. 
Uploaded 
The problem comes from the fact that Git adds `-master` to the plugin folder name. Before uploading to the plugin page, it must be unpacked, renamed and packed again ... I don't like git adding `-master` suffix to project folder.

**Comment by pcav** [comment]
Thanks
